version: '3.8'


services:
  db:
    image: postgres:16
    container_name: "library_db"
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  library_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
          condition: service_healthy
    command: sh -c "alembic upgrade head && python3 main.py"

volumes:
  postgres: